    <compras>
        <detalleCompras>
            <codSustento>${codSus}</codSustento>
            <tpIdProv>${tipoId}</tpIdProv>
            <idProv>${identificaion}</idProv>
            <tipoComprobante>${tipoComp}</tipoComprobante>
            <parteRel>${parteRel}</parteRel>
            <fechaRegistro>${fecRegistro}</fechaRegistro>
            <establecimiento>${estab}</establecimiento>
            <puntoEmision>${punto}</puntoEmision>
            <secuencial>${numero}</secuencial>
            <fechaEmision>${fecEmi}</fechaEmision>
            <autorizacion>${auto}</autorizacion>
            <baseNoGraIva>${baseNoIva}</baseNoGraIva>
            <baseImponible>${baseImpo}</baseImponible>
            <baseImpGrav>${baseImpoGrav}</baseImpGrav>
            <baseImpExe>${baseImpoExe}</baseImpExe>
            <montoIce>${montoIce}</montoIce>
            <montoIva>${montoIva}</montoIva>
            <valRetBien10>${valRetBi10}</valRetBien10>
            <valRetServ20>${valRetSe20}</valRetServ20>
            <valorRetBienes>${valRetBi}</valorRetBienes>
            <valRetServ50>0.00</valRetServ50>
            <valorRetServicios>${valRetSe}</valorRetServicios>
            <valRetServ100>${valRetSe100}</valRetServ100>
            <totbasesImpReemb>${totBaseImpRee}</totbasesImpReemb>
            <pagoExterior>
                <pagoLocExt>${pagoLocExt}</pagoLocExt>
                <paisEfecPago>${pais}</paisEfecPago>
                <aplicConvDobTrib>${aplicaConv}</aplicConvDobTrib>
                <pagExtSujRetNorLeg>${pagoExtSuj}</pagExtSujRetNorLeg>
                <pagoRegFis>${pagoRegFis}</pagoRegFis>
            </pagoExterior>
